
services:
  app:
    image: python:alpine
    # build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    container_name: quote-gen-core-api-dev
    stdin_open: true    # Keep stdin open
    tty: true           # Allocate a pseudo-TTY
